### ISSUE TITLE
Error while running `yarn run start` command.

### ISSUE THREAD

**Issue by 19akshansh** [sanikava/Sanikava-Search#1]
I was setting up the Repository & while Running `yarn` command, I got this in console:
![Screenshot_20220131-125058_Termux.jpg](https://user-images.githubusercontent.com/78315967/151753531-697ff680-fe94-4359-8dd1-9d332aee636b.jpg)

& After Running `yarn run start` command, I got this Error in console:
![Screenshot_20220131-125159_Termux.jpg](https://user-images.githubusercontent.com/78315967/151753649-560a46bf-018d-4ff4-b451-89359d18eccf.jpg)

**Comment by sanikava** [comment]
it will not work in android sorry
